name: CI/CD Deploy to EC2

on:
  push:
    branches: [ "main" ] # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.239.124.209
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Update and install Docker if not present
            sudo yum update -y
            sudo yum install docker -y
            sudo service docker start
            sudo usermod -aG docker ec2-user

            # 2. Login to Docker Hub using the GitHub Secret (Secure way)
            echo "${{ secrets.DOCKER_TOKEN }}" | sudo docker login -u alejandromoraecheverry --password-stdin

            # 3. Stop and remove existing container if it exists
            sudo docker stop cicd-hello || true
            sudo docker rm cicd-hello || true

            # 4. Pull the latest image from Docker Hub
            sudo docker pull xbgmaster/cicd-hello:latest

            # 5. Run the new container mapping port 80 to 3000
            sudo docker run -d -p 80:3000 xbgmaster/cicd-hello:latest